# Workflow Requirements:
#
# 1. In repository Settings -> Actions -> General, ensure "Allow all actions and reusable workflows" is selected, and that under "Workflow permissions", "Read repository contents and packages permissions" is checked.
# 2. On https://hub.docker.com click your username in the top right, then Account Settings, then select "Security" from the left nav menu; generate a new Access Token for this repo with read & write perms.
# 3. In repository Settings -> Secrets and variables -> Actions, create a new Repository secret; call it ``DOCKERHUB_TOKEN`` and paste the Docker Hub access token you just created as the value.
#
name: Release on Tag
on:
  push:
    tags:
    - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        run: echo "${{secrets.GITHUB_TOKEN}}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: jantman
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Build and Push
        uses: docker/build-push-action@v4
        with:
          push: true
          sbom: true
          labels: |
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.version=${{ github.ref_name }}
            org.opencontainers.image.revision=${{ github.sha }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}:latest
            ${{ github.repository }}:${{ github.ref_name }}
            ${{ github.repository }}:latest
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release ${{ github.ref_name }}.

            **GitHub Package:** https://github.com/users/jantman/packages/container/package/machine-access-control

            **Docker Images:**
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}:latest
            ${{ github.repository }}:${{ github.ref_name }}
            ${{ github.repository }}:latest
          draft: false
          prerelease: false
